using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class BlockHealthSyncModel 
{
    [RealtimeProperty(1, true, true)]
    private int _health;
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class BlockHealthSyncModel : RealtimeModel {
    public int health {
        get {
            return _cache.LookForValueInCache(_health, entry => entry.healthSet, entry => entry.health);
        }
        set {
            if (this.health == value) return;
            _cache.UpdateLocalCache(entry => { entry.healthSet = true; entry.health = value; return entry; });
            InvalidateReliableLength();
            FireHealthDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(BlockHealthSyncModel model, T value);
    public event PropertyChangedHandler<int> healthDidChange;
    
    private struct LocalCacheEntry {
        public bool healthSet;
        public int health;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Health = 1,
    }
    
    public BlockHealthSyncModel() : this(null) {
    }
    
    public BlockHealthSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireHealthDidChange(int value) {
        try {
            healthDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Health, (uint)_health);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.healthSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Health, (uint)entry.health);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.Health, (uint)_health);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.healthSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.healthSet) {
                stream.WriteVarint32((uint)PropertyID.Health, (uint)entry.health);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Health: {
                    int previousValue = _health;
                    _health = (int)stream.ReadVarint32();
                    bool healthExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.healthSet);
                    if (!healthExistsInChangeCache && _health != previousValue) {
                        FireHealthDidChange(_health);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _health = health;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
