using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ColorSyncModel_Carlos
{
    [RealtimeProperty(1, true, true)]
    private Color _color;

    [RealtimeProperty(2, false, true)]
    private Vector3 _position;
    [RealtimeProperty(3, false, true)]
    private Quaternion _rotation;
    [RealtimeProperty(4, false, true)]
    private Vector3 _scale;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ColorSyncModel_Carlos : RealtimeModel {
    public UnityEngine.Vector3 position {
        get {
            return _position;
        }
        set {
            if (_position == value) return;
            _positionShouldWrite = true;
            _position = value;
            InvalidateUnreliableLength();
            FirePositionDidChange(value);
        }
    }
    
    public UnityEngine.Quaternion rotation {
        get {
            return _rotation;
        }
        set {
            if (_rotation == value) return;
            _rotationShouldWrite = true;
            _rotation = value;
            InvalidateUnreliableLength();
            FireRotationDidChange(value);
        }
    }
    
    public UnityEngine.Vector3 scale {
        get {
            return _scale;
        }
        set {
            if (_scale == value) return;
            _scaleShouldWrite = true;
            _scale = value;
            InvalidateUnreliableLength();
            FireScaleDidChange(value);
        }
    }
    
    public UnityEngine.Color color {
        get {
            return _cache.LookForValueInCache(_color, entry => entry.colorSet, entry => entry.color);
        }
        set {
            if (this.color == value) return;
            _cache.UpdateLocalCache(entry => { entry.colorSet = true; entry.color = value; return entry; });
            InvalidateReliableLength();
            FireColorDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ColorSyncModel_Carlos model, T value);
    public event PropertyChangedHandler<UnityEngine.Color> colorDidChange;
    public event PropertyChangedHandler<UnityEngine.Vector3> positionDidChange;
    public event PropertyChangedHandler<UnityEngine.Quaternion> rotationDidChange;
    public event PropertyChangedHandler<UnityEngine.Vector3> scaleDidChange;
    
    private struct LocalCacheEntry {
        public bool colorSet;
        public UnityEngine.Color color;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    private bool _positionShouldWrite;
    private bool _rotationShouldWrite;
    private bool _scaleShouldWrite;
    
    public enum PropertyID : uint {
        Color = 1,
        Position = 2,
        Rotation = 3,
        Scale = 4,
    }
    
    public ColorSyncModel_Carlos() : this(null) {
    }
    
    public ColorSyncModel_Carlos(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireColorDidChange(UnityEngine.Color value) {
        try {
            colorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FirePositionDidChange(UnityEngine.Vector3 value) {
        try {
            positionDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireRotationDidChange(UnityEngine.Quaternion value) {
        try {
            rotationDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireScaleDidChange(UnityEngine.Vector3 value) {
        try {
            scaleDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteBytesLength((uint)PropertyID.Position, WriteStream.Vector3ToBytesLength());
            length += WriteStream.WriteBytesLength((uint)PropertyID.Rotation, WriteStream.QuaternionToBytesLength());
            length += WriteStream.WriteBytesLength((uint)PropertyID.Scale, WriteStream.Vector3ToBytesLength());
            length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
        } else if (context.unreliableChannel) {
            if (_positionShouldWrite) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Position, WriteStream.Vector3ToBytesLength());
            }
            if (_rotationShouldWrite) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Rotation, WriteStream.QuaternionToBytesLength());
            }
            if (_scaleShouldWrite) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Scale, WriteStream.Vector3ToBytesLength());
            }
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.colorSet) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteBytes((uint)PropertyID.Position, WriteStream.Vector3ToBytes(_position));
            _positionShouldWrite = false;
            stream.WriteBytes((uint)PropertyID.Rotation, WriteStream.QuaternionToBytes(_rotation));
            _rotationShouldWrite = false;
            stream.WriteBytes((uint)PropertyID.Scale, WriteStream.Vector3ToBytes(_scale));
            _scaleShouldWrite = false;
            stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(_color));
        } else if (context.unreliableChannel) {
            if (_positionShouldWrite) {
                _positionShouldWrite = false;
                stream.WriteBytes((uint)PropertyID.Position, WriteStream.Vector3ToBytes(_position));
                didWriteProperties = true;
            }
            if (_rotationShouldWrite) {
                _rotationShouldWrite = false;
                stream.WriteBytes((uint)PropertyID.Rotation, WriteStream.QuaternionToBytes(_rotation));
                didWriteProperties = true;
            }
            if (_scaleShouldWrite) {
                _scaleShouldWrite = false;
                stream.WriteBytes((uint)PropertyID.Scale, WriteStream.Vector3ToBytes(_scale));
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateUnreliableLength();
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.colorSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.colorSet) {
                stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(entry.color));
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Color: {
                    UnityEngine.Color previousValue = _color;
                    _color = ReadStream.ColorFromBytes(stream.ReadBytes());
                    bool colorExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.colorSet);
                    if (!colorExistsInChangeCache && _color != previousValue) {
                        FireColorDidChange(_color);
                    }
                    break;
                }
                case (uint)PropertyID.Position: {
                    UnityEngine.Vector3 previousValue = _position;
                    _position = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    _positionShouldWrite = false;
                    if (_position != previousValue) {
                        FirePositionDidChange(_position);
                    }
                    break;
                }
                case (uint)PropertyID.Rotation: {
                    UnityEngine.Quaternion previousValue = _rotation;
                    _rotation = ReadStream.QuaternionFromBytes(stream.ReadBytes());
                    _rotationShouldWrite = false;
                    if (_rotation != previousValue) {
                        FireRotationDidChange(_rotation);
                    }
                    break;
                }
                case (uint)PropertyID.Scale: {
                    UnityEngine.Vector3 previousValue = _scale;
                    _scale = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    _scaleShouldWrite = false;
                    if (_scale != previousValue) {
                        FireScaleDidChange(_scale);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _color = color;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
